### ISSUE TITLE
Bread crumb names on camp pages don't always agree with "as of" setting names in the camp tree.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#650] opened 2020-10-05 15:56 UTC
Change the "as of" value, and notice that the bread crumb names don't always agree with the camp names in the tree structure.

**Comment by gautamv16** [comment] 2020-12-13 18:48
@BrentAllsop I have tested this but not able to reproduce it, so for now closing it

**Closed as completed by gautamv16** 2020-12-13 18:48 UTC
Labels: bug
