### ISSUE TITLE
In the Camp edit page, need a preview button

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#58] opened 2018-05-15 10:28 UTC
* In the actual edit page, we need a preview button so the user can verify they have everything correct, before they do the submit.

**Comment by BrentAllsop** [comment] 2018-07-12 04:26
This is an involved fix, but very important.
Higher priority than any other "Fix Soon" issue.

**Comment by gautamv16** [comment] 2018-09-29 06:49
@BrentAllsop and @rupalichavan9860 please check the preview button on camp edit and statement edit page.

**Comment by rupalichavan9860** [comment] 2018-09-29 11:51
@gautamv16 Tested functionality of preview button on statement update page.I found following issues
1. Incorrect date is displaying for "Go Live Time"
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create a fresh topic and add camp statement
4. Using same user try to update added camp statement
5. Click on "Preview" button
6. Observe Statement preview pop up for "Go Live Time"
7. Now click on "Statement Update" button
8. Observe "Camp Statement History" page for "Go Live Time" for recently updated record

Expected Result : 
Because submitter is updating the statement "Go Live Time" should be today's date
"Go Live Time" on Statement preview pop up and "Camp Statement History" should be same

Actual Result : 
"Go Live Time"date is displaying different on Statement preview pop up 

![image](https://user-images.githubusercontent.com/40416610/46245416-eaa1f600-c40a-11e8-96a7-d623e08de8a2.png)

![image](https://user-images.githubusercontent.com/40416610/46245424-00afb680-c40b-11e8-8180-44158c45b035.png)

**Comment by rupalichavan9860** [comment] 2018-09-29 12:11
@gautamv16 @BrentAllsop I think Preview button should be present on "Add Camp Statement" also so that user can see preview of  whatever he/she is adding in statement field.Please confirm
Is there any need of Preview button on "Camp Update" page?Because user is not adding any statement on Camp update page

**Comment by gautamv16** [comment] 2018-09-29 16:51
@rupalichavan9860 Preview is required on camp edit majorly. But i have also added on statement too. I dont think its required on add as we need to preview on update to compare it with existing.

Have done some issue remaining please retest

**Comment by rupalichavan9860** [comment] 2018-09-30 09:41
@gautamv16 Incorrect date is displaying for "Go Live Time" this issue is still exists.Please fix this issue.I have added details above with screenshots.please check

**Comment by gautamv16** [comment] 2018-10-01 06:28
@rupalichavan9860 please check

**Comment by rupalichavan9860** [comment] 2018-10-01 08:31
@gautamv16 "Go Live Time" issue is still exists.As submitter is trying to submit the statement update "Go Live Time" should be today's date only and not 1 week after .
**Go Live Time is displaying correctly on Camp Statement History,But not on Statement Review
Please check this again**
![image](https://user-images.githubusercontent.com/40416610/46277917-59558f80-c582-11e8-88c4-56fde0efddb3.png)

![image](https://user-images.githubusercontent.com/40416610/46277945-6d00f600-c582-11e8-86d3-9b399917bd0a.png)

**Comment by gautamv16** [comment] 2018-10-01 09:03
Go live time will display 1 week after date. its correct.

@rupalichavan9860 when ever we try to object anything it will be in review for 1 week so it will dissplay date after 1 week but when it is submitted actual live time will be calculated based on the records i.e If we dont have any current live or there is no other reason for not going live then it will be live instantly. So either we have to remove go live date from preview or we must have to keep this logic as we dont have instant go live date untill its not submitted. According to me its correct.

**Comment by rupalichavan9860** [comment] 2018-10-01 09:15
@gautamv16 Yes that is okay.But if Statement submitter is trying to update his/her own record then the "Go live time" date  on Camp Statement History is displaying same as "Submitted On" date but not only on "Statement review".
Please go through the steps I have provided and check again

**Comment by rupalichavan9860** [comment] 2018-10-02 08:43
@gautamv16 Retested and as per discussion I can see Submitted On and Go Live Time fields are removed from preview pop up.So I m closing this issue

**Comment by BrentAllsop** [comment] 2018-11-30 19:39
This is working for when you modify the existing text of a statement.
But the create new statement page is missing this preview button.

To reproduce: Create a new camp, then press the "Add Camp Statement" button.
There is no preview button on this add statement page.

**Comment by rupalichavan9860** [comment] 2018-12-03 09:28
@gautamv16 Brent reopened this issue .Please check

**Comment by gautamv16** [comment] 2018-12-17 12:05
@BrentAllsop please check this one and close. Its developed as per your requirement on add feature.

**Comment by BrentAllsop** [comment] 2018-12-17 22:24
Yup, tested.  Looks great so closing.

**Closed as completed by BrentAllsop** 2018-12-17 22:24 UTC
Labels: enhancement, Fixed, Re-Opened, 8th Release
