### ISSUE TITLE
Create Topic functionality is not working properly for "Other" namespace

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#140] opened 2018-06-29 16:41 UTC
Create new topic with "Other" as a Namespace,topic should get added under "Other" Namespace,now it is getting added under "General" Namespace.

**Comment by gautamv16** [comment] 2018-07-04 09:37
This is not a bug. When we select other that means user will submit a namespace and it will go to the review of admin and when admin will aprove it, it will display otherwise it will be general. So this feature will be done in next release.

**Comment by gautamv16** [comment] 2018-09-10 07:45
closing this issue as its related to 152.

**Closed as completed by gautamv16** 2018-09-10 07:45 UTC
Labels: enhancement, Next Release
