### ISSUE TITLE
When you create a new topic, add support to root camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#54] opened 2018-05-08 18:33 UTC
When you create a new topic, this also creates a root camp.
By default, the submitter should be added as a supporter of this root camp.

**Comment by gautamv16** [comment] 2018-05-10 09:11
@BrentAllsop  please test this with creating new topic.

**Comment by BrentAllsop** [comment] 2018-05-10 14:24
I tested this on staging.canonizer.com.
But the topic I created had no support.

**Comment by gautamv16** [comment] 2018-05-15 05:55
@BrentAllsop solved this now.

**Comment by BrentAllsop** [comment] 2018-05-15 20:45
@gautamv16,
tested and closing.

**Comment by BrentAllsop** [comment] 2018-11-28 20:34
This is a slightly different use case, (dealing with camps, instead of topics).
But it also deals with adding support by default to newly created items, so re-opening this enhancement.

When a person creates a new camp, they should be initially added as a supporter of that camp by default.  It can be generalized to the topic case, since when you create a topic, you also create the agreement camp.  Again, when this, or any camp is created, the user should be added as a supporter.

**Comment by gautamv16** [comment] 2018-12-20 10:57
@BrentAllsop and @rupalichavan9860 please test it as intended. Its working same as per requirement.

**Comment by BrentAllsop** [comment] 2018-12-20 22:34
Tested this, and looks great.
@rupalichavan9860 if this looks OK to you, go ahead and close it.

**Comment by rupalichavan9860** [comment] 2018-12-23 16:45
It looks Ok to me also so closing this

**Closed as completed by rupalichavan9860** 2018-12-23 16:45 UTC
Labels: Feature, Fixed, 8th Release
