### ISSUE TITLE
Parent camp is not showing correctly for the child camp on Production

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1104] opened 2022-01-28 06:13 UTC
Go to https://canonizer.com/topic/369-Regression-25-JAN-2022-updated/1-Agreement
Camp 3 parent camp is Agreement , but in the tree it is showing '1'.

Check the screenshots for better understanding.
![Screenshot 2022-01-28 at 11 40 15 AM](https://user-images.githubusercontent.com/91254708/151496619-37b42d6e-895a-44b2-9faf-99765b10ba5f.png)
![Screenshot 2022-01-28 at 11 40 55 AM](https://user-images.githubusercontent.com/91254708/151496644-91d9ea9c-5634-4143-96de-1efbacaddfbc.png)

**Comment by saniatg** [comment] 2022-02-23 06:31
@rupalichavan9860 not able to reproduce the issue for now. Can you also confirm.

**Comment by rupalichavan9860** [comment] 2022-02-23 06:43
Not able to reproduce so closing this issue

**Closed as completed by rupalichavan9860** 2022-02-23 06:43 UTC
Labels: bug, 30th Release
