### ISSUE TITLE
First letter of all the providers must be Capital

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1117] opened 2022-02-02 08:17 UTC
Navigate to  Social Oauth Verification module.
All the Provides first letter must be Capital.
![Screenshot 2022-02-02 at 1 46 45 PM](https://user-images.githubusercontent.com/91254708/152117396-28faa43e-c344-4ce5-8928-8f757aee5fa3.png)

**Comment by saniatg** [comment] 2022-02-22 13:27
@cd-ali-ehsan 
Provider LinkedIn name is incorrect. 'I ' letter must be capital. It should be 'LinkedIn' not Linkedin
![Screenshot 2022-02-22 at 6 57 07 PM](https://user-images.githubusercontent.com/91254708/155141712-9a7d5038-c6c1-4bc8-9a9d-bb2141dec523.png)

**Comment by rupalichavan9860** [comment] 2022-02-22 14:01
User is unable to link social accounts and we observed below change 

Screenshot of Staging : 

![image](https://user-images.githubusercontent.com/40416610/155147573-c25cb634-591b-4a6e-9407-527f5efde35c.png)


Screenshot of live: 

![image](https://user-images.githubusercontent.com/40416610/155147592-b91287a3-205b-4244-a948-cb7b6f99891e.png)

**Comment by saniatg** [comment] 2022-02-25 12:06
@ahmed130544  user is not able to link the social accounts.

**Comment by rupalichavan9860** [comment] 2022-03-04 10:09
Tested and verified. As of now user is able to link and unlink social accounts but sometimes user need to click multiple times on unlink to unlink account.
we are unable to reproduce the scenario so as of now closing this

**Comment by sonalizibtek** [comment] 2022-03-09 05:31
Working fine, Tested and Verified. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment] 2022-03-09 08:01
Verified

**Closed as completed by rupalichavan9860** 2022-03-09 08:01 UTC
Labels: bug, 29th Release
