### ISSUE TITLE
Open link in new tab for link "logged in username" is displaying blank page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#183] opened 2018-07-11 09:22 UTC
Steps to reproduce:
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Right click on logged in username link and click on "Open link in new tab"

Expected Result:
It should open same page in new tab

Actual Result:
It is opening blank page

![image](https://user-images.githubusercontent.com/40416610/42562620-d6405d1c-8519-11e8-8df9-2ec4277ec36d.png)

![image](https://user-images.githubusercontent.com/40416610/42562609-cfad6d50-8519-11e8-98a9-d25ff8247660.png)

**Comment by gautamv16** [comment] 2018-07-11 09:28
@rupalichavan9860 this is useless issue. Its not an issue.

**Comment by rupalichavan9860** [comment] 2018-07-11 09:34
@gautamv16 This is an issue and not useless issue.There are standard test cases for links you can check on internet.
test case for links: Test to check if there are any blank page to link

**Comment by gautamv16** [comment] 2018-07-11 09:55
@rupalichavan9860 this is useless interms of our functionality and feature of the canonizer. There is no link for username and its not necessary in any test case that a link always have a url and must be directed to a page. So it has no use here. I have checked all test cases and this is not required and have no use here.

**Comment by rupalichavan9860** [comment] 2018-07-11 10:06
@BrentAllsop Please clarify.

**Comment by gautamv16** [comment] 2018-07-11 10:36
@rupalichavan9860 @BrentAllsop in any term this is not a bug and this is very much clarified to @rupalichavan9860 but she is not ready to understand. @rupalichavan9860 must have to agree on things which are explained. This ticket is completely out of scope and invalid. username is name under which a menu item is opening so its not required to open same on on its right click open in new tab. Hope your explaination let her understand it.

**Comment by rupalichavan9860** [comment] 2018-07-11 11:10
@gautamv16  Okay.Fair enough.I clearly understood the issue but just wanted to confirm with Brent.If this is functionality and you are okay then I will close this one.Also please note I am agree with what you explained but my job is to confirm once again.Also there is no bug/issue which is tagged as useless.I am not testing according to developer.
I hope no more explanation required on this.Thanks

**Comment by gautamv16** [comment] 2018-07-11 11:16
@rupalichavan9860 discussion is very important and required for correct decision makings. You arenot testing as per developer and that is very good. And this is not an issue / bug according to my past decades experience, this is just result of testing. But it must be related to the application and flow and user usecases, it must not be forced on developer once it is confirmed. If there is no need of my help for such questions and tickets then mention all tickets to @BrentAllsop to confirm that is it bug or not if its bugs then i will reply on that, hope this will help you.

**Comment by BrentAllsop** [comment] 2018-07-12 03:56
After discussing, we realized this is a problem with the drop down, which is out of our control.
We would have no way to make it go to another page, without breaking the drop down functionality.
So we are going to close this issue.

**Closed as completed by BrentAllsop** 2018-07-12 03:56 UTC
Labels: invalid, wontfix
