### ISSUE TITLE
Submitting forum post causes fatal error.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#251] opened 2018-09-12 20:55 UTC
I submitted a post to a forum of this agreement camp:

https://staging.canonizer.com/topic/30-Attorney-Test-Topic/1

and got this fatal error:

(1/1) ErrorExceptionUndefined variable: camp_id
--
in CommonForumFunctions.php line 42
at HandleExceptions->handleError(8, 'Undefined variable: camp_id', '/var/www/html/canonizer-staging/app/CommonForumFunctions.php', 42, array('topicid' => '30', 'campnum' => '1', 'link' => 'forum/30-Attorney-Test-Topic/1/threads/209', 'post' => 'This is a Wed Sep 12 test post to this forum.', 'threadId' => '209', 'nick_id' => '1', 'bcc_email' => array(''), 'camp' => object(Camp), 'subCampIds' => array(1, 4, 3, 5, 2), 'topic_name' => 'Attorney Test Topic', 'camp_name' => 'Agreement', 'data' => array('post' => 'This is a Wed Sep 12 test post to this forum.', 'camp_name' => 'Agreement', 'thread' => object(Collection), 'subject' => 'Attorney Test Topic / Agreement / from thread post submitted.')))in CommonForumFunctions.php line 42
at CommonForumFunctions::sendEmailToSupportersForumPost('30', '1', 'forum/30-Attorney-Test-Topic/1/threads/209', 'This is a Wed Sep 12 test post to this forum.', '209', '1')in ReplyController.php line 68
at ReplyController->store('30', 'Attorney-Test-Topic', '1', '209', object(Request))
at call_user_func_array(array(object(ReplyController), 'store'), array('topicid' => '30', 'topicname' => 'Attorney-Test-Topic', 'campnum' => '1', 'thread' => '209',object(Request)))in Controller.php line 55

**Comment by rupalichavan9860** [comment] 2018-09-13 03:56
@BrentAllsop @akuks I have also tested camp forum for emails functionality.While creating new thread I am getting "Swift_RfcComplianceException"
Please refer following screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/45466368-059c1700-b737-11e8-8c5d-731ae5810b55.png)

**Comment by rupalichavan9860** [comment] 2018-09-13 03:59
@BrentAllsop @akuks When I am trying to reply to the thread post I am getting another error exception than above
Please refer screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/45466423-60357300-b737-11e8-8154-13b40526083a.png)

**Comment by akuks** [comment] 2018-09-13 07:22
The issue is related to #246

**Comment by akuks** [comment] 2018-09-13 07:29
#246 --> It will be fixed with Issue 246

**Comment by rupalichavan9860** [comment] 2018-09-14 14:36
@akuks I have tested Forum emails functionality.Error exception issue is fixed and supporters are getting mail now,but needs some UI changes in mail format
Missing things:
1. Header - Canonizer
2. Footer - © 2018 Canonizer. All rights reserved.
3. Alignment - Alignment should be center
It should be like other canonizer emails for uniformity.Please check attached screenshot for more details

Expected : 
Please follow format like below mail
![image](https://user-images.githubusercontent.com/40416610/45556482-03ca7480-b859-11e8-8e1a-ed7be75f8f82.png)

![image](https://user-images.githubusercontent.com/40416610/45556550-265c8d80-b859-11e8-9769-f6f336046757.png)

Actual : 
![image](https://user-images.githubusercontent.com/40416610/45556583-396f5d80-b859-11e8-9171-409add884d62.png)

**Comment by akuks** [comment] 2018-09-18 07:30
@rupalichavan9860 Please Test

**Comment by rupalichavan9860** [comment] 2018-09-19 08:59
@akuks Tested and working good.Closing this

**Closed as completed by rupalichavan9860** 2018-09-19 08:59 UTC
Labels: bug, Show Stopper
